"""followers

Revision ID: 625d280845fa
Revises: f62719a50d86
Create Date: 2021-07-18 21:10:24.932870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625d280845fa'
down_revision = 'f62719a50d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
